### ISSUE TITLE
Database error: Database error: UNIQUE constraint failed: All_.id

### ISSUE THREAD

**Issue by ChristopherCarignan** [cartoon-raccoon/cogsy#1]
I'm getting this error when initializing the Database for the first time:

`Database error: Database error: UNIQUE constraint failed: All_.id`

I have some albums with multiple copies, which I'm thinking is the causing the issue. Database cannot be initialized and cogsy fails and exits accordingly.

**Comment by cartoon-raccoon** [comment]
Alright, I've pushed a patch that should fix the issue.

I've managed to replicate the bug on my own machine, so it's an actual problem in my code. You can check the commit history to see how I fixed it.

I've tested the new version and it works on my machine now. Hope it's the same for yours.
